"""empty message

Revision ID: 62f54aa6da95
Revises: 63bf856b277b
Create Date: 2025-10-20 22:00:18.214097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f54aa6da95'
down_revision: Union[str, Sequence[str], None] = '63bf856b277b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'product',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'product',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
