"""empty message

Revision ID: 6d7149d49027
Revises: b23026993c4f
Create Date: 2025-10-20 22:02:00.914625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7149d49027'
down_revision: Union[str, Sequence[str], None] = 'b23026993c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'address_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
