"""empty message

Revision ID: e292b61a5018
Revises: 8e68589dd0ea
Create Date: 2025-10-27 08:36:13.581338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e292b61a5018'
down_revision: Union[str, Sequence[str], None] = '8e68589dd0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    op.drop_table('products')
    # ### end Alembic commands ###
